global:
  scrape_interval:     3s

  external_labels:
      monitor: 'example-app'

rule_files:

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['python:5555']

#   - job_name: 'example'

#     dns_sd_configs:
#       - names: ['app']
#         port: 5000
#         type: A
#         refresh_interval: 5s

# global:
#   scrape_interval:     5s
#   evaluation_interval: 30s
# scrape_configs:

# - job_name: my-application
#   honor_labels: true
#   static_configs:
#   - targets: ['python:5555']