# Use root/example as user/password credentials
version: '3.1'

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: test
      MYSQL_USER: root
    ports:
      - 3306:3306
    volumes:
      - /home/osboxes/Public/mysqldb:/var/lib/mysql
